//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PHBLT
    {
        public long ID { get; set; }
        public string C_9HBTP { get; set; }
        public string C_9HBDC { get; set; }
        public string C_9SITU { get; set; }
        public string C_9USCR { get; set; }
        public Nullable<System.DateTime> C_9DTCR { get; set; }
        public Nullable<System.DateTime> C_9HOCR { get; set; }
    }
}
