//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PPAIS
    {
        public long ID { get; set; }
        public string C_ASPAI { get; set; }
        public string C_ACPAI { get; set; }
        public Nullable<int> C_ANPAI { get; set; }
        public string C_ADPAI { get; set; }
        public string C_AINDI { get; set; }
        public string C_ACID1 { get; set; }
        public string C_ACID2 { get; set; }
        public string C_ACID3 { get; set; }
        public string C_ASITU { get; set; }
        public string C_AUSCR { get; set; }
        public Nullable<int> C_ADTCR { get; set; }
        public Nullable<int> C_AHOCR { get; set; }
        public string C_AUSDE { get; set; }
        public Nullable<int> C_ADTDE { get; set; }
        public Nullable<int> C_AHODE { get; set; }
    }
}
