//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PTIDD
    {
        public long ID { get; set; }
        public string C_PTITP { get; set; }
        public string C_PTIDC { get; set; }
        public string C_POLOC { get; set; }
        public string C_PSITU { get; set; }
        public string C_PPASD { get; set; }
        public string C_PIDTIPUTL { get; set; }
        public string C_PIDRCLCKD { get; set; }
        public string C_PIDPARM1 { get; set; }
        public string C_PIDPARM2 { get; set; }
        public string C_PIDTRCKDG { get; set; }
        public Nullable<int> C_PIDCARMIN { get; set; }
        public Nullable<int> C_PIDCARMAX { get; set; }
    }
}
