//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerAccountsEntities : DbContext
    {
        public CustomerAccountsEntities()
            : base("name=CustomerAccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_PACTP> C_PACTP { get; set; }
        public virtual DbSet<C_PESTC> C_PESTC { get; set; }
        public virtual DbSet<C_PHBLT> C_PHBLT { get; set; }
        public virtual DbSet<C_PPAIS> C_PPAIS { get; set; }
        public virtual DbSet<C_PPROF> C_PPROF { get; set; }
        public virtual DbSet<GBTIT> GBTIT { get; set; }
        public virtual DbSet<C_PREGC> C_PREGC { get; set; }
        public virtual DbSet<C_PTIDD> C_PTIDD { get; set; }
        public virtual DbSet<GBCRES> GBCRES { get; set; }
        public virtual DbSet<GBCSTE> GBCSTE { get; set; }
        public virtual DbSet<GBCSTR> GBCSTR { get; set; }
        public virtual DbSet<GBTPENT> GBTPENT { get; set; }
        public virtual DbSet<CTMOV> CTMOV { get; set; }
        public virtual DbSet<FGCMB> FGCMB { get; set; }
        public virtual DbSet<FGGCOT> FGGCOT { get; set; }
        public virtual DbSet<GBCCC> GBCCC { get; set; }
        public virtual DbSet<GBCCO> GBCCO { get; set; }
        public virtual DbSet<GBCCR> GBCCR { get; set; }
        public virtual DbSet<GBCDO> GBCDO { get; set; }
        public virtual DbSet<GBCDP> GBCDP { get; set; }
        public virtual DbSet<GBCLI> GBCLI { get; set; }
        public virtual DbSet<GBCNDM> GBCNDM { get; set; }
        public virtual DbSet<GBCODOP> GBCODOP { get; set; }
        public virtual DbSet<GBLTIT> GBLTIT { get; set; }
        public virtual DbSet<GBMORD> GBMORD { get; set; }
        public virtual DbSet<GBMVCC> GBMVCC { get; set; }
        public virtual DbSet<GBMVCO> GBMVCO { get; set; }
        public virtual DbSet<GBMVCR> GBMVCR { get; set; }
        public virtual DbSet<GBMVDO> GBMVDO { get; set; }
        public virtual DbSet<GBMVDP> GBMVDP { get; set; }
        public virtual DbSet<GBNATR> GBNATR { get; set; }
        public virtual DbSet<GBOPR> GBOPR { get; set; }
        public virtual DbSet<GBTCLI> GBTCLI { get; set; }
        public virtual DbSet<GBTRCLI> GBTRCLI { get; set; }
    }
}
