//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGCMB_Divisas
    {
        public int CBDATC_CBTCOT_CBMOED { get; set; }
        public Nullable<int> CBDATC_DataCotacao { get; set; }
        public string CBTCOT_TipoCotacao { get; set; }
        public string CBMOED_Moeda { get; set; }
        public string CBMOEB_MoedaBase { get; set; }
        public Nullable<decimal> CBCOMP_Compra { get; set; }
        public Nullable<decimal> CBVEND_Venda { get; set; }
        public Nullable<int> CBDATG_DataDeGravacao { get; set; }
        public Nullable<int> CBHORA_HoraDeGravacao { get; set; }
        public string CBUSGR_UtilizadorGravacao { get; set; }
    
        public virtual FGTCOT_TiposCotacao FGTCOT_TiposCotacao { get; set; }
        public virtual PMOEDA_Divisas PMOEDA_Divisas { get; set; }
    }
}
