//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGGCOT_GeracaoCotacoes
    {
        public int CJMOED_CJTCOT { get; set; }
        public string CJMOEB_MoedaBase { get; set; }
        public string CJMOED_Moeda { get; set; }
        public string CJTCOT_TipoCotacao { get; set; }
        public Nullable<decimal> CJPCMP_PercentagemParaCompra { get; set; }
        public Nullable<decimal> CJPVND_PercentagemParaVenda { get; set; }
        public string CJVARC_VariacaoParaCompra { get; set; }
        public string CJVARV_VariacaoParaVenda { get; set; }
    
        public virtual FGTCOT_TiposCotacao FGTCOT_TiposCotacao { get; set; }
        public virtual PMOEDA_Divisas PMOEDA_Divisas { get; set; }
    }
}
