//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FGTCOT_TiposCotacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FGTCOT_TiposCotacao()
        {
            this.FGCMB_Cambios = new HashSet<FGCMB_Cambios>();
            this.FGGCOT_GeracaoCotacoes = new HashSet<FGGCOT_GeracaoCotacoes>();
        }
    
        public string TOTCOT_TipoCotacao { get; set; }
        public string TODCOT_Descritivo { get; set; }
        public string TODSC_DisponivelModuloSc { get; set; }
        public string TOINDC_IndicadorCotacao { get; set; }
        public string FGTORECCV_RecolheCâmbioCompraVenda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FGCMB_Cambios> FGCMB_Cambios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FGGCOT_GeracaoCotacoes> FGGCOT_GeracaoCotacoes { get; set; }
    }
}
