//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCODOP_CodigosOperacao
    {
        public int COCOPE_CodigoOperacao { get; set; }
        public Nullable<int> COCOPA_CdgOperacaoAnulacao { get; set; }
        public Nullable<int> COTDOC_TipoDocumento { get; set; }
        public string CODESC_DescritivoCdgOper { get; set; }
        public string CODEST_DescritivoTipoDoc { get; set; }
        public string CODBCR_DebitoOuCredito { get; set; }
        public string COPERD_PodeSerPerdido { get; set; }
        public string COCTV_PodeSerCativo { get; set; }
        public string COPLC_PodeLibertarCativo { get; set; }
        public string COLVDF_LancaParaValorDiferente { get; set; }
        public string COCHEQ_TipoDocCheques { get; set; }
        public string CODEV_CodigoEDevolucao { get; set; }
        public string COCOES_PodeSerEstornado { get; set; }
        public string COAVLR_AdmiteValoresParaCativar { get; set; }
        public string COSCTV_SaldoCativoAAfectar { get; set; }
        public string CONVLP_NivelProteccao { get; set; }
        public string CODRCX_ValidoEmDiarioCaixa { get; set; }
        public string CONDDV_NrDiasParaDataValor { get; set; }
        public string COTDDV_TipoDiasParaDataValor { get; set; }
        public string CONDCT_NrDiasParaCativo { get; set; }
        public string COTDCT_TipoDiasParaCativo { get; set; }
        public string COCKDG_ValidaCheckDigit { get; set; }
        public string COVIBA_ParmVisadoOuBancario { get; set; }
        public string COCZIB_CativoObrigaZib { get; set; }
        public string COCOAU_CativoExigeAutorizacao { get; set; }
        public string COCVDS_CativoValidaDescoberto { get; set; }
        public string COTSAC_SaldoCreditoAAfectar { get; set; }
        public string CODOAU_DescativoExigeAutoriz { get; set; }
        public Nullable<int> COBALC_BalcaoCcbPorDefeito { get; set; }
        public string COCCB_ContaContabPorDefeito { get; set; }
        public string COTRV_ParmTransitoValores { get; set; }
        public string COTVLR_TipoValorColectavel { get; set; }
        public string COMINV_MovimentoInvisivel { get; set; }
        public Nullable<int> COCNOT_CodigoNota { get; set; }
        public string CODMOV_DescritivoMovimento { get; set; }
        public string COBSIT_BypassNaSituacaoDoc { get; set; }
        public Nullable<int> COPCD_PosicaoConcatDocumento { get; set; }
        public string COCDCX_CertificaDocCaixa { get; set; }
        public string COTTYP_TipoTransaccaoParaSwift { get; set; }
        public Nullable<decimal> COVLR_ValorDespesas { get; set; }
        public string COMOEV_MoedaDespesas { get; set; }
        public string CODMOVDES_DescMovimDespesas { get; set; }
        public Nullable<decimal> COFACT_FactorDespesas { get; set; }
        public Nullable<decimal> COVLRM_ValorMinimo { get; set; }
        public Nullable<decimal> COVLRX_ValorMaximo { get; set; }
        public string COMOEM_MoedaMinimoMaximo { get; set; }
        public string COTISN_TipoIsencao { get; set; }
        public Nullable<decimal> COVISN_ValorIsencao { get; set; }
        public string COMOEI_MoedaIsencao { get; set; }
        public string COTARR_TipoArredondamento { get; set; }
        public Nullable<int> COCNOTA_CodigoNotaDespesas { get; set; }
        public string COSITU_Situacao { get; set; }
        public string COUSSI_UtilizadorSituacao { get; set; }
        public Nullable<int> CODTSI_DataSituacao { get; set; }
        public Nullable<int> COHOSI_HoraSituacao { get; set; }
        public string GBCOCRMOV_ComRestricoesMov { get; set; }
    }
}
