//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCRES_CodigosResidencia
    {
        public long ID { get; set; }
        public string RECRES_CodigoResidencia { get; set; }
        public string REDESC_Descritivo { get; set; }
    }
}
