//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCSTR
    {
        public long ID { get; set; }
        public string SRCST { get; set; }
        public string SRSLT { get; set; }
        public string SRDESC { get; set; }
        public string SROCPA { get; set; }
        public string SRVALE { get; set; }
    }
}
