//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCSTE
    {
        public long ID { get; set; }
        public string SECST { get; set; }
        public string SESLT { get; set; }
        public string SEDESC { get; set; }
        public string SEOCPA { get; set; }
        public string SEVALE { get; set; }
    }
}
