//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCSTE_CodigosSectoriaisNaoResidentes
    {
        public string SECST_CodigoSectorial { get; set; }
        public string SESLT_Seleccionavel { get; set; }
        public string SEDESC_Descritivo { get; set; }
        public string SEOCPA_ObrigatorioCdgPais { get; set; }
        public string SEVALE_ValidoEm { get; set; }
    }
}
