//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBCSTR_CodigosSectoriaisResidentes
    {
        public string SRCST_CodigoSectorial { get; set; }
        public string SRSLT_Seleccionavel { get; set; }
        public string SRDESC_Descritivo { get; set; }
        public string SROCPA_ObrigatorioCdgPais { get; set; }
        public string SRVALE_ValidoEm { get; set; }
    }
}
