//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBDOC_Documentos
    {
        public long ID_Documentos { get; set; }
        public int DCTDOC_TipoDocumento { get; set; }
        public int DCNDOC_Documento { get; set; }
        public string DCSITU_SituacaoDocumento { get; set; }
        public int DCANOI_Ano { get; set; }
    }
}
