//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBNATR_NaturezasContas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GBNATR_NaturezasContas()
        {
            this.GBCCC_ContasCaucionadas = new HashSet<GBCCC_ContasCaucionadas>();
            this.GBMORD_Moradas = new HashSet<GBMORD_Moradas>();
        }
    
        public int NTNATR_Natureza { get; set; }
        public string NTDESC_Descritivo { get; set; }
        public string NTDESR_DescritivoReduzido { get; set; }
        public Nullable<int> NTNULC_NrMaximoContas { get; set; }
        public string NTTSLD_TipoSaldo { get; set; }
        public string NTCLCP_ClasseComponente { get; set; }
        public string NTTNSC_TipoParaNatrSemContas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBCCC_ContasCaucionadas> GBCCC_ContasCaucionadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBMORD_Moradas> GBMORD_Moradas { get; set; }
    }
}
