//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBNATR_NaturezasContas
    {
        public int NTNATR_Natureza { get; set; }
        public string NTDESC_Descritivo { get; set; }
        public string NTDESR_DescritivoReduzido { get; set; }
        public Nullable<int> NTNULC_NrMaximoContas { get; set; }
        public string NTTSLD_TipoSaldo { get; set; }
        public string NTCLCP_ClasseComponente { get; set; }
        public string NTTNSC_TipoParaNatrSemContas { get; set; }
    }
}
