//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBOPR_Operacoes
    {
        public int X1NOPR_NumeroOperacao { get; set; }
        public string X1SITU_SituacaoOperacao { get; set; }
        public string X1MVES_MovimentosEstornados { get; set; }
        public Nullable<int> X1HORA_HoraInicioExecucao { get; set; }
        public Nullable<int> X1DTIN_DataInicioExecucao { get; set; }
        public string X1TTTR_TipoTransaccao { get; set; }
    }
}
