//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBTCLI_SegmentoCliente
    {
        public string TCTIPO_Tipo { get; set; }
        public string TCDESC_Descritivo { get; set; }
        public string TCPBAL_SoPermitidoNosBalcoes { get; set; }
    }
}
