//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBTIT_Entidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GBTIT_Entidade()
        {
            this.GBLTIT_LigacaoClientesEntidades = new HashSet<GBLTIT_LigacaoClientesEntidades>();
            this.GBMORD_Moradas = new HashSet<GBMORD_Moradas>();
            this.GBMVCO_MovimentosContasContabilisticas = new HashSet<GBMVCO_MovimentosContasContabilisticas>();
        }
    
        public int TTNUMT_NrEntidade { get; set; }
        public string TTTIPT_EmpresaOuParticular { get; set; }
        public string TTNOMT_NomeEntidade { get; set; }
        public string TTNOME_NomeSemTitulo { get; set; }
        public string TTNOMR_NomeReduzido { get; set; }
        public Nullable<int> TTDNSC_DataNascimento { get; set; }
        public string TTSEXO_Sexo { get; set; }
        public string TTHABL_Habilitacoes { get; set; }
        public string TTACTP_ActividadeProfissional { get; set; }
        public string GBTTPROF_Profissao { get; set; }
        public string GBTTTIPIDF_TipoIdentificacaoFiscal { get; set; }
        public string TTNIF_NrIdentificacaoFiscal { get; set; }
        public Nullable<int> TTBAIR_ReparticaoFiscal { get; set; }
        public string GBTTCTGFSC_CategoriaFiscal { get; set; }
        public string TTTIDE_TipoIdentificacao { get; set; }
        public string TTNIDE_NrIdentificacao { get; set; }
        public Nullable<int> GBTTCKDGID_CheckDigitIdentificacao { get; set; }
        public string TTLOCA_LocalEmissao { get; set; }
        public Nullable<int> TTDTEI_DataEmissao { get; set; }
        public Nullable<int> GBTTDTVAL_DataValidadeDocumento { get; set; }
        public string GBTTNUMACO_NrMatriculaConservatoria { get; set; }
        public string GBTTNOCONS_NomeConservatoria { get; set; }
        public string GBTTNUPBDO_NrPublicacaoDiarioOficial { get; set; }
        public string TTNAC_Nacionalidade { get; set; }
        public string TTNATU_Naturalidade { get; set; }
        public string TTECIV_EstadoCivil { get; set; }
        public string TTRCAS_RegimeCasamento { get; set; }
        public string TTPAI_NomePai { get; set; }
        public string TTMAE_NomeMae { get; set; }
        public string TTENTP_EntidadePatronal { get; set; }
        public string TTFUCA_FuncaoOuCargo { get; set; }
        public Nullable<int> TTDTAD_DataAdmissao { get; set; }
        public string TTTSOC_TipoSociedade { get; set; }
        public string TTCAE_CodigoActividadeEconomica { get; set; }
        public string GBTTCAESC_CodigoActividadeEconomicaSecundario { get; set; }
        public Nullable<int> TTDTCT_DataConstituicao { get; set; }
        public Nullable<int> TTDTPB_DataPublicacao { get; set; }
        public string TTSEDE_DomicilioOuSede { get; set; }
        public Nullable<long> TTCSRA_CapitalSocialOuRendimentoAnual { get; set; }
        public string TTMOED_MoedaCsra { get; set; }
        public string TTVINC_VinculoComOutras { get; set; }
        public Nullable<long> TTNCTR_NrCentralRisco { get; set; }
        public string TTCRES_CodigoResidencia { get; set; }
        public string TTCST_CodigoSectorial { get; set; }
        public string TTPAIS_CodigoPais { get; set; }
        public string TTTPEN_TipoEntidade { get; set; }
        public string TTBLOQ_ComBloqueios { get; set; }
        public string GBTTALER_ComAlertas { get; set; }
    
        public virtual GBCRES_CodigosResidencia GBCRES_CodigosResidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBLTIT_LigacaoClientesEntidades> GBLTIT_LigacaoClientesEntidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBMORD_Moradas> GBMORD_Moradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBMVCO_MovimentosContasContabilisticas> GBMVCO_MovimentosContasContabilisticas { get; set; }
        public virtual PPROF_Profissoes PPROF_Profissoes { get; set; }
        public virtual PTIDD_TiposIdentificacao PTIDD_TiposIdentificacao { get; set; }
        public virtual PACTP_ActividadeProfissional PACTP_ActividadeProfissional { get; set; }
        public virtual PESTC_EstadoCivil PESTC_EstadoCivil { get; set; }
        public virtual PHBLT_HabilitacoesLiterarias PHBLT_HabilitacoesLiterarias { get; set; }
        public virtual PMOEDA_Divisas PMOEDA_Divisas { get; set; }
        public virtual PPAIS_Paises PPAIS_Paises { get; set; }
        public virtual PPAIS_Paises PPAIS_Paises1 { get; set; }
        public virtual PREGC_RegimesCasamento PREGC_RegimesCasamento { get; set; }
        public virtual PTIDD_TiposIdentificacao PTIDD_TiposIdentificacao1 { get; set; }
        public virtual GBTPENT_TiposEntidades GBTPENT_TiposEntidades { get; set; }
    }
}
