//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBTIT
    {
        public long ID { get; set; }
        public Nullable<int> TTNUMT { get; set; }
        public string TTTIPT { get; set; }
        public string TTNOMT { get; set; }
        public string TTNOME { get; set; }
        public string TTNOMR { get; set; }
        public Nullable<int> TTDNSC { get; set; }
        public string TTSEXO { get; set; }
        public string TTHABL { get; set; }
        public string TTACTP { get; set; }
        public string GBTTPROF { get; set; }
        public string GBTTTIPIDF { get; set; }
        public string TTNIF { get; set; }
        public Nullable<int> TTBAIR { get; set; }
        public string GBTTCTGFSC { get; set; }
        public string TTTIDE { get; set; }
        public string TTNIDE { get; set; }
        public Nullable<int> GBTTCKDGID { get; set; }
        public string TTLOCA { get; set; }
        public Nullable<int> TTDTEI { get; set; }
        public Nullable<int> GBTTDTVAL { get; set; }
        public string GBTTNUMACO { get; set; }
        public string GBTTNOCONS { get; set; }
        public string GBTTNUPBDO { get; set; }
        public string TTNAC { get; set; }
        public string TTNATU { get; set; }
        public string TTECIV { get; set; }
        public string TTRCAS { get; set; }
        public string TTPAI { get; set; }
        public string TTMAE { get; set; }
        public string TTENTP { get; set; }
        public string TTFUCA { get; set; }
        public Nullable<int> TTDTAD { get; set; }
        public string TTTSOC { get; set; }
        public string TTCAE { get; set; }
        public string GBTTCAESC { get; set; }
        public Nullable<int> TTDTCT { get; set; }
        public Nullable<int> TTDTPB { get; set; }
        public string TTSEDE { get; set; }
        public Nullable<int> TTCSRA { get; set; }
        public string TTMOED { get; set; }
        public string TTVINC { get; set; }
        public Nullable<int> TTNCTR { get; set; }
        public string TTCRES { get; set; }
        public string TTCST { get; set; }
        public string TTPAIS { get; set; }
        public string TTTPEN { get; set; }
        public string TTBLOQ { get; set; }
        public string GBTTALER { get; set; }
    }
}
