//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBTPENT_TiposEntidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GBTPENT_TiposEntidades()
        {
            this.GBTIT_Entidade = new HashSet<GBTIT_Entidade>();
        }
    
        public string NITPEN_TipoEntidade { get; set; }
        public string NIDTPE_Descritivo { get; set; }
        public string NIPRCV_ProcessoValido { get; set; }
        public string NICOUR_ComunicaParaUtilizadoresRisco { get; set; }
        public string NICOCR_ComunicaParaCentralRisco { get; set; }
        public Nullable<int> GBNIIDMIN_IdadeMinima { get; set; }
        public Nullable<int> GBNIIDMAX_IdadeMaxima { get; set; }
        public string NIUSCR_UtilizadorCriacao { get; set; }
        public Nullable<int> NIDTCR_DataCriacao { get; set; }
        public Nullable<int> NIHOCR_HoraCriacao { get; set; }
        public string NISITU_Situacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBTIT_Entidade> GBTIT_Entidade { get; set; }
    }
}
