//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBTRCLI_TiposRelacoesEntidadesClientes
    {
        public string RTRCLI_RelacaoComCliente { get; set; }
        public string RTSORD_SeqOrdenacao { get; set; }
        public string RTDESC_Descritivo { get; set; }
        public string RTVCPR_ValidoCliPart { get; set; }
        public string RTVCEP_ValidoCliEmpresa { get; set; }
        public string RTSLDT_InfluenciaSldTit { get; set; }
        public string RTPRCH_PodeReqCheques { get; set; }
        public string RTCOUR_ComunicaParaUtilRisco { get; set; }
        public string RTCOCR_ComunicaParaCentRisco { get; set; }
        public string RTSITU_Situacao { get; set; }
        public Nullable<int> RTDTCR_DataCriacao { get; set; }
        public Nullable<int> RTHOCR_HoraCriacao { get; set; }
        public string RTUSCR_UtilizadorCriacao { get; set; }
    }
}
