//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESTC_EstadoCivil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PESTC_EstadoCivil()
        {
            this.GBTIT_Entidade = new HashSet<GBTIT_Entidade>();
        }
    
        public string EECIV_EstadoCivil { get; set; }
        public string EDCIV_Descritivo { get; set; }
        public string ERCAV_RegimesCasamentoValidos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBTIT_Entidade> GBTIT_Entidade { get; set; }
        public virtual PREGC_RegimesCasamento PREGC_RegimesCasamento { get; set; }
    }
}
