//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESTC_EstadoCivil
    {
        public string EECIV_EstadoCivil { get; set; }
        public string EDCIV_Descritivo { get; set; }
        public string ERCAV_RegimesCasamentoValidos { get; set; }
    }
}
