//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHBLT_HabilitacoesLiterarias
    {
        public long ID { get; set; }
        public string C9HBTP_Habilitacoes { get; set; }
        public string C9HBDC_Descritivo { get; set; }
        public string C9SITU_Situacao { get; set; }
        public string C9USCR_UtilizadorCriacao { get; set; }
        public Nullable<System.DateTime> C9DTCR_DataCriacao { get; set; }
        public Nullable<System.DateTime> C9HOCR_HoraCriacao { get; set; }
    }
}
