//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPROF_Profissoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PPROF_Profissoes()
        {
            this.GBTIT_Entidade = new HashSet<GBTIT_Entidade>();
        }
    
        public string PPRPROF_CodigoProfissao { get; set; }
        public string PPRDESC_Descritivo { get; set; }
        public string PPRACTV_CdgActividadeValidos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBTIT_Entidade> GBTIT_Entidade { get; set; }
    }
}
