//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerAccountsPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTIDD_TiposIdentificacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PTIDD_TiposIdentificacao()
        {
            this.GBTIT_Entidade = new HashSet<GBTIT_Entidade>();
            this.GBTIT_Entidade1 = new HashSet<GBTIT_Entidade>();
        }
    
        public string PTITP_TipoIdentificacao { get; set; }
        public string PTIDC_Descritivo { get; set; }
        public string POLOC_ObrigaLocalEmissao { get; set; }
        public string PSITU_Situacao { get; set; }
        public string PPASD_PermiteAssociarSeDesactivado { get; set; }
        public string PIDTIPUTL_TipoUtilizacao { get; set; }
        public string PIDRCLCKD_RotinaCalculoCheckDigit { get; set; }
        public string PIDPARM1_Parametro1ParaRotina { get; set; }
        public string PIDPARM2_Parametro2ParaRotina { get; set; }
        public string PIDTRCKDG_TratamentoParaCheckDigit { get; set; }
        public Nullable<int> PIDCARMIN_NrMinimoCaracteres { get; set; }
        public Nullable<int> PIDCARMAX_NrMaximoCaracteres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBTIT_Entidade> GBTIT_Entidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBTIT_Entidade> GBTIT_Entidade1 { get; set; }
    }
}
